[tools]
biome = "2.5.13"
lefthook = "2.1.12"
node = "24.16.0"
pnpm = "12.4.1"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.setup]
run = [
  "pnpm install",
  "panda codegen --clean",
  "pnpm exec playwright install"
]
