name: Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Code Quality"]
    branches: [master]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.repository_owner == 'bsmg') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Mise
        uses: jdx/mise-action@v4
      - name: Prepare
        run: mise run setup
      - name: Build
        run: |
          vite build
          cp ./dist/index.html ./dist/404.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
