name: Code Quality

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

env:
  YARN_ENABLE_HARDENED_MODE: 0

jobs:
  check:
    name: Run Quality Checks (Biome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Mise
        uses: jdx/mise-action@v4
      - name: Run Biome
        run: biome ci --diagnostic-level=error .
  test:
    name: Run Unit Tests (Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Mise
        uses: jdx/mise-action@v4
      - name: Prepare
        run: mise run prepare
      - name: Run Vitest
        run: vitest run
