name: Code Quality

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

env:
  NODE_VERSION: 20.x
  YARN_ENABLE_HARDENED_MODE: 0

jobs:
  check:
    name: Run Quality Checks (Biome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.1.3
      - name: Run Biome
        run: biome ci --diagnostic-level=error .
  test:
    name: Run Unit Tests (Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Prepare
        run: yarn prepare
      - name: Run Vitest
        run: yarn test run
